### ISSUE TITLE
Mail notification send all

### ISSUE THREAD

**Issue by panostzemis** [rhpds/gitea-operator#11]
Hello,

We setup email notification on our GITEA. Whenever a PR is open it send an email to the approver but it also sends in CC to all GITEA users. We tried to change the settings on email notification to "send mails on mention" but that does not works at all and it does not send a message to anyone. 

Is there something that has to be done from your side as operator handlers, or is it an extra configuration that has to take place?
Thank you a lot

**Comment by wkulhanek** [comment]
@panostzemis No idea. I haven't seen this behavior. If there is a specific app.ini setting you can now provide your app.ini in a configmap: https://github.com/rhpds/gitea-operator#provide-appini-in-configmap
