### ISSUE TITLE
Dockerfile for quay.io/gpte-devops-automation/gitea

### ISSUE THREAD

**Issue by apfelchips** [rhpds/gitea-operator#15]
Hi, you pull `quay.io/gpte-devops-automation/gitea` as your gitea default container image. Have the Dockerfile and the support files for that container been published anywhere? 

All I can see is that the container is based on `ubi/ubi8-minimal` , installs some dependencies  and downloads the gitea binary from gitea.io.

Container Buildsteps: https://quay.io/repository/gpte-devops-automation/gitea/manifest/sha256:09487cc411cd1823e6ef9b7172f25bedfc446d23cd1bb76580cd426f9910c9c6

https://github.com/redhat-gpte-devopsautomation/gitea-operator/blob/master/roles/gitea-ocp/defaults/main.yml#L20

**Comment by johankok** [comment]
It's probably located at https://github.com/wkulhanek/docker-openshift-gitea, the `build.sh` script there pushes to `quay.io/gpte-devops-automation/gitea`.

**Comment by wkulhanek** [comment]
@apfelchips @johankok  Everything was moved to the rhpds organization in both Github and Quay for the release of V2 yesterday.

The link provided by @johankok was correct - now it is https://github.com/rhpds/openshift-gitea-image.
