### ISSUE TITLE
[RFE] Allow webhook configuration

### ISSUE THREAD

**Issue by agiertli** [rhpds/gitea-operator#16]
I tried to setup a gitea webhook, with target URL pointing to ArgoCD server.

Initially, it failed with:

`Delivery: Post "https://openshift-gitops-server-openshift-gitops.apps.cluster-dnh92.dnh92.sandbox1352.opentlc.com/api/webhook": x509: certificate is valid for openshift-gitops, openshift-gitops-grpc, openshift-gitops.openshift-gitops.svc.cluster.local, not openshift-gitops-server-openshift-gitops.apps.cluster-dnh92.dnh92.sandbox1352.opentlc.com`

So I switched to service URL (instead of route, since my gitea and ArgoCD are located in a same cluster) but then it failed with :

`Delivery: Post "http://openshift-gitops-server.openshift-gitops.svc.cluster.local/api/webhook": dial tcp 172.30.222.199:80: webhook can only call allowed HTTP servers (check your webhook.ALLOWED_HOST_LIST setting), deny 'openshift-gitops-server.openshift-gitops.svc.cluster.local(172.30.222.199:80)'`

Both of these errors can be solved by configuring app.ini, but sadly, that's not possible currently.

This RFE is about allowing following properties to be configurable via Gitea CR:

webhook.ALLOWED_HOST_LIST
webhook.SKIP_TLS_VERIFY

source: https://docs.gitea.io/en-us/config-cheat-sheet/

Unfortunately, at the moment, these defects makes gitea webhooks not usable.

**Comment by stas-at-ibm** [comment]
I am having the same issue. Is there at least a workoraround? The `app.ini` is deployed in a config map `gitea-config` but no changes to it are possible.

@agiertli have you solved it?

**Comment by wkulhanek** [comment]
@agiertli @stas-at-ibm This is now (finally) implemented: Note that the operator was refreshed - including a new api group.

giteaWebhookAllowedHostList:
  description: List of hosts that a web hook is allowed to call. See https://docs.gitea.com/next/administration/config-cheat-sheet#webhook-webhook for more details. Default is 'external,private'.
  type: string
giteaWebhookSkipTlsVerify:
  description: Set to 'true' to skip validation of the webhook target URL certificate. Default is false.
  type: boolean
