### ISSUE TITLE
Edit Service Configuration  (app.ini)

### ISSUE THREAD

**Issue by panostzemis** [rhpds/gitea-operator#7]
I have some configurations on the Gitea installation but I am not sure how I may change them.
![image](https://user-images.githubusercontent.com/8168360/125782280-706d7065-5750-468b-b7e0-915bed692d1e.png)

Let's say I want to allow Enable OpenID Self-Registration and Enable OpenID Sign-In.

Thank you in advance

**Comment by wkulhanek** [comment]
@panostzemis Right now you can't. The app.ini is generated and stored immutable in a ConfigMap based on the Operator spec. What's not in the operator spec can't be changed.

I'm pretty sure this would require somewhat of a rewrite. I can't even just allow you to embed an app.ini in the Operator CR - it would need the hostname that Gitea is running on. Which you wouldn't know upfront.

**Comment by wkulhanek** [comment]
@panostzemis It sure took long enough... but the V2 version of the operator that I just released now has the capability to provide an app.ini from a ConfigMap - you also need to specify the hostname but at least now you can customize the config to your heart's content if necessary.

**Comment by wkulhanek** [comment]
https://github.com/rhpds/gitea-operator#provide-appini-in-configmap
