### ISSUE TITLE
 SSH Configuration enabled but no service is created.

### ISSUE THREAD

**Issue by panostzemis** [rhpds/gitea-operator#8]
![image](https://user-images.githubusercontent.com/8168360/125782592-e4c8ead1-f6e6-411c-a0b6-12780f1427d1.png)

SSH is enabled but no service has been created and no port 2022 exists on deployment yaml. Only the 3000 that the gitea is installed by default.

![image](https://user-images.githubusercontent.com/8168360/125782788-631431af-a3a7-4654-9c01-e0e24d3955b7.png)

Please let me know if something extra actions are required.

**Comment by wkulhanek** [comment]
@panostzemis I never got that to work. Can you try to set this up manually and let me know if you get it to work?

**Comment by panostzemis** [comment]
Could you please elaborate on "manually" that you are saying in your comment ?.Is the SSH ready on gitea? Should I just create a Service and deployment file for it ?

**Comment by wkulhanek** [comment]
@panostzemis actually looking even that won't be enough because the Pod only listens on port 3000/TCP. I'd have to add 2022/TCP as well. I'll keep this in the backlog once I come up for air to work on this.

**Comment by panostzemis** [comment]
Great, Thank you @wkulhanek .
Let us know once you do that :) 
Thank you for your operator.

**Comment by wkulhanek** [comment]
@panostzemis You can now change the app.ini yourself by providing a ConfigMap. If there is a specific app.ini setting you can now provide your app.ini in a configmap: https://github.com/rhpds/gitea-operator#provide-appini-in-configmap. For SSH outside of the cluster you will probably need a node port service or similar.
